### ISSUE TITLE
recover pubkey by signature in cosmos ecosystem.

### ISSUE THREAD

**Issue by 99Kies** [ctrl-Felix/mospy#13]
I want to recover my public key by signature, is there any way?

**Comment by 99Kies** [comment]
`this code is not verified`

```python
        a = ECDSA()

        sig_raw = bytes(bytearray.fromhex(signature))
        sig = a.ecdsa_recoverable_deserialize(sig_raw, revid)
        msg = bytes().fromhex(message)
        pubkey = a.ecdsa_recover(msg, sig)

        res_pub_bytes = show_public(PublicKey(pubkey))
        print(binascii.b2a_hex(res_pub_bytes))

        addr_by_pub = pubkey_to_address(res_pub_bytes, hrp="evmos")
        return  addr_by_pub == address
```

**Comment by ctrl-Felix** [comment]
I am not sure if what you want to achieve is possible: https://crypto.stackexchange.com/questions/9936/what-signature-schemes-allow-recovering-the-public-key-from-a-signature

May I ask what the specific usecase is?

**Comment by 99Kies** [comment]
@ctrl-Felix The method of recover `publickey` of `secp256k1` has been implemented by many libraries. The method I have above is working, but I didn't find how cosmos does the signing. Can your `mospy-sdk` implement signing of a small message(such as: `hello`...)? (Can you send me the signed message and signature and address?) We can improve this method together.

**Comment by 99Kies** [comment]
I was looking for a front-end demo to do a signature test, 😂, but never found one.

**Comment by 99Kies** [comment]
> May I ask what the specific usecase is?

This function is mainly used for backend address binding.
