### ISSUE TITLE
Cannot run the example code for creating, signing and encoding a transaction

### ISSUE THREAD

**Issue by mostafamshk** [ctrl-Felix/mospy#15]
Hey :)
I am using this library to create transactions and sign them. I followed docs example and tried to run my code . 
but I get some confusing error that I don't know anything about it. this my code :
(notice that I'm using this code for my own `cosmos-sdk`-based blockchain. This is why `denom` and address formats are customized)
 
```
import httpx
from mospy import Account, Transaction

account = Account(
    seed_phrase="[my-mnemonic]"
)

tx = Transaction(
    account=account,
    gas=1000,
)
tx.set_fee(
    amount=2500,
    denom="nbkc"
)
tx.add_msg(
    tx_type='transfer',
    sender=account,
    receipient="[some-valid-address]",
    amount=1000000000,
    denom="nbkc"
)
tx_bytes = tx.get_tx_bytes_as_string()

print(tx_bytes);
```
and this the error I get when i run the command `python3 main.py`: 
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from mospy import Account, Transaction
  File "/usr/local/lib/python3.8/dist-packages/mospy/__init__.py", line 1, in <module>
    from .Account import Account
  File "/usr/local/lib/python3.8/dist-packages/mospy/Account.py", line 4, in <module>
    from mospy.utils import privkey_to_address
  File "/usr/local/lib/python3.8/dist-packages/mospy/utils.py", line 7, in <module>
    from sha3 import keccak_256
  File "/usr/local/lib/python3.8/dist-packages/sha3.py", line 8, in <module>
    from _pysha3 import keccak_224, keccak_256, keccak_384, keccak_512
ImportError: /usr/local/lib/python3.8/dist-packages/_pysha3.cpython-38-x86_64-linux-gnu.so: undefined symbol: Py_SET_TYPE
```

**Comment by ctrl-Felix** [comment]
It seems that you are using pyrthon3.8 which is not compatible with safe-pysha3. Actually I've just merged #14 which is a PR which solves exactly that. I am pushing a new updated version of mospy today which will be the v0.4 release which should then also support python3.8.

Otherwise you could try to use 3.9+ which works with with the current version

**Comment by ctrl-Felix** [comment]
I've pushed mospy 0.4

**Comment by mostafamshk** [comment]
Hi Felix :))
Thank you very much for you support and hard work. I installed the 0.4 version and it worked !
You made my day honestly.
