### ISSUE TITLE
how to use Mnemonic seed generated within (Trust wallet) with your SDK

### ISSUE THREAD

**Issue by animencoding** [ctrl-Felix/mospy#17]
Hello first of all thank you for this awesome SDK and sorry in advance if this issue is not related to the project, but i figured people here will know more about this

I'm having an issue using my trust wallet seed which has a cosmos address within this lib 

when i run the example with the trust wallet seed the address differ from the one in my trust wallet

do you have any info regarding this?

thanks!

**Comment by ctrl-Felix** [comment]
Trust wallet might be using a different derivation path or a different slip44 value. These would be my first ideas. Besides that maybe they have modified the account index. 

You could try to play with these values a bit

**Comment by l33r3** [comment]
what coin?
