### ISSUE TITLE
can make a tia or inj address?

### ISSUE THREAD

**Issue by viponedream** [ctrl-Felix/mospy#20]
can make a tia or inj address?

**Comment by viponedream** [comment]
injective  has the different address between keplr

**Comment by ctrl-Felix** [comment]
Injective is using 60 as slip44 value

https://github.com/cosmos/chain-registry/blob/master/injective/chain.json#L13

The Tia one is the same as the default so that should work. I will give it a try later today

**Comment by viponedream** [comment]
thank for your replay.
but injective addr is still wrong.

    account = Account(
        seed_phrase = seed_phrase ,
        address_index = 0,
        hrp = 'inj',
        slip44 = 60,
    )
    print(f'addr: {account.address}')

**Comment by ctrl-Felix** [comment]
Celestia works for me

```python
account = Account(
    seed_phrase="",
    hrp="celestia"
)
```

I've just checked Inj, they are using the eth algorithm. Pass eth=True on the Account instantiation and you should be fine
