### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by viponedream** [ctrl-Felix/mospy#21]
just run your example code

  File "C:\Python310\lib\site-packages\mospy\Transaction.py", line 178, in _get_signer_infos
    signer_infos.sequence = self._account.next_sequence
TypeError: 'NoneType' object cannot be interpreted as an integer

import httpx # optional
from mospy import Account, Transaction

account = Account(
    seed_phrase="law grab theory better athlete submit awkward hawk state wedding wave monkey audit blame fury wood tag rent furnace exotic jeans drift destroy style",
    address_index=12
)

tx = Transaction(
    account=account,
    gas=1000,
)
tx.set_fee(
    amount=100,
    denom="uatom"
)
# Add a transfer message to the transaction (multiple messages can be added)
tx.add_msg(
    tx_type='transfer',
    sender=account,
    receipient="cosmos1tkv9rquxr88r7snrg42kxdj9gsnfxxg028kuh9",
    amount=1000,
    denom="uatom"
)

# Sign and encode transaction to submit it to the network manually

# REST endpoint (RPC or API)
tx_bytes = tx.get_tx_bytes_as_string()

**Comment by viponedream** [comment]
File "C:\Python310\lib\site-packages\mospy\Transaction.py", line 178, in _get_signer_infos
    signer_infos.sequence = self._account.next_sequence

self._account.next_sequence is None, so error happen

but i run your test_transaction.py,  it runs well

**Comment by ctrl-Felix** [comment]
It seems like I forgot to add the sequence in that example. The sequence is a counter indicating how many transactions have been made from the account

**Comment by ctrl-Felix** [comment]
https://mospy.ctrl-felix.de/examples/

Check out the examples to see how to set it

**Comment by viponedream** [comment]
your another example set it to 1,
is it like nonce in eth network? 
can you write a example to exectue batch transactions?
