### ISSUE TITLE
can not send a transaction

### ISSUE THREAD

**Issue by viponedream** [ctrl-Felix/mospy#22]
injective chain can not send a transaction

rest_url = 'https://lcd-injective.keplr.app'
    
    chain_id = 'injective-1'
    denom = 'inj'
    hrp = 'inj'
    slip44 = 60
    eth = True
the address now is correct,

while post , it respone  tx parse error

**Comment by viponedream** [comment]
{
  "tx_response": {
    "height": "0",
    "txhash": "9C2E575F57D7583A2C7C5EC114DCF9C2D9411C47ED61C14AE92BA6EFCD4059B4",
    "codespace": "sdk",
    "code": 2,
    "data": "",
    "raw_log": "unable to resolve type URL /ethermint.crypto.v1.ethsecp256k1.PubKey: tx parse error",
    "logs": [
    ],
    "info": "",
    "gas_wanted": "0",
    "gas_used": "0",
    "tx": null,
    "timestamp": "",
    "events": [
    ]
  }
}

**Comment by ctrl-Felix** [comment]
Hi, I found the error for that. I will make a patch in the upcoming days

**Comment by l33r3** [comment]
> Hi, I found the error for that. I will make a patch in the upcoming days

same trouble. can u fix it soon?

**Comment by ctrl-Felix** [comment]
I just pushed v0.5.1 which fixes the Injective bug
