### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by viponedream** [ctrl-Felix/mospy#29]
{"tx_response":{"height":"0","txhash":"9A8157B27A79A7DCFACBBCADB0078FB7891342424F5283A6BC422EE2803A12A4","codespace":"sdk","code":4,"data":"","raw_log":"signature verification failed; please verify account number (2780) and chain-id (joltifydev_1730-1): unauthorized","logs":[],"info":"","gas_wanted":"0","gas_used":"0","tx":null,"timestamp":"","events":[]}}

**Comment by ctrl-Felix** [comment]
Please reopen if issue still persists.
